import { Property, AreaProfile, Testimonial, ServiceItem, FAQItem, BlogPost } from '../types';

export const COMPANY_DETAILS = {
  name: 'Karni Property',
  tagline: 'Property Dealer in Jodhpur',
  address: 'Sardarpura, Jodhpur, Rajasthan',
  phone: '+91 98765 43210',
  secondaryPhone: '+91 291 265 4321',
  whatsapp: '+91 98765 43210',
  email: 'karniproperty.jodhpur@gmail.com',
  workingHours: 'Mon - Sat: 9:30 AM - 8:30 PM | Sunday: By Appointment',
  googleRating: 4.9,
  googleReviewCount: 480,
  yearsOfExperience: 14,
  propertiesRentedCount: 1850,
  happyClientsCount: 2400,
  commercialDealsCount: 620,
};

export const PROPERTIES_DATA: Property[] = [
  {
    id: 'prop-1',
    title: 'Marwar Heritage Royal Villa with Private Courtyard',
    price: 85000,
    period: '/mo',
    displayPrice: '₹85,000/mo',
    category: 'Residential',
    propertyType: 'Luxury Villa',
    status: 'For Rent',
    location: 'Sardarpura, Jodhpur',
    address: 'Road No. 3, Near Circuit House, Sardarpura, Jodhpur',
    areaSqFt: 3400,
    bedrooms: 4,
    bathrooms: 4,
    parking: 3,
    facing: 'North-East',
    floor: 'Independent House (G+1)',
    furnishedStatus: 'Furnished',
    isExclusive: true,
    tag: 'EXCLUSIVE LUXURY',
    images: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1200&q=80',
    ],
    description: 'An exquisite 4 BHK Marwari heritage luxury villa located in the prestigious heart of Sardarpura. Featuring traditional Jodhpur sandstone pillars, expansive modular kitchen, Italian marble flooring, lush green lawn, and private servant quarters. Perfect for corporate executives, doctors, or joint families.',
    amenities: [
      'Private Sandstone Lawn',
      'Fully Modular Italian Kitchen',
      '100% Power Backup Generator',
      'Covered Car Parking (3 Cars)',
      'Solar Water Heater',
      'CCTV 24/7 Security',
      'Vastu Compliant Design',
      'Servant Room with Attached Washroom'
    ],
    nearbyPlaces: [
      { name: 'Circuit House Road Market', distance: '0.4 km', category: 'Market' },
      { name: 'Goyal Hospital & Research Centre', distance: '1.2 km', category: 'Hospital' },
      { name: 'St. Anne\'s Senior Secondary School', distance: '1.5 km', category: 'School' },
      { name: 'Jodhpur Railway Station', distance: '3.8 km', category: 'Transport' },
      { name: 'Jodhpur Airport', distance: '5.2 km', category: 'Airport' },
    ],
    agent: {
      name: 'Ramesh Gehlot',
      role: 'Senior Rental Advisor',
      phone: '+91 98765 43210',
      whatsapp: '+91 98765 43210',
      email: 'ramesh.karniproperty@gmail.com',
      image: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=400&q=80',
    },
    dateListed: '2026-07-20',
  },
  {
    id: 'prop-2',
    title: 'Skyline Commercial Glass Tower Office Suite',
    price: 55000,
    period: '/mo',
    displayPrice: '₹55,000/mo',
    category: 'Office Space',
    propertyType: 'Office Suite',
    status: 'For Rent',
    location: 'Shastri Nagar, Jodhpur',
    address: '4th Floor, Apex Trade Tower, Opposite Medical College, Shastri Nagar',
    areaSqFt: 1450,
    bathrooms: 2,
    parking: 2,
    facing: 'Main Road Facing',
    floor: '4th Floor (High Speed Lift)',
    furnishedStatus: 'Furnished',
    isHotDeal: true,
    tag: 'HOT COMMERCIAL DEAL',
    images: [
      'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1200&q=80',
    ],
    description: 'Ready-to-occupy corporate office space with 18 workstations, 2 director cabins, 1 conference room for 10 people, reception desk, pantry, and dedicated IT server rack. Ideal for IT companies, chartered accountants, legal firms, or corporate regional offices in Shastri Nagar.',
    amenities: [
      'Centralized Air Conditioning',
      'High-Speed Fiber Internet Ready',
      '10-Seater Glass Conference Room',
      'Modern Reception & Waiting Lounge',
      '24/7 Security with Biometric Access',
      'Dual Elevator Access',
      'In-house Cafeteria & Pantry',
      'Reserved Basement Parking'
    ],
    nearbyPlaces: [
      { name: 'Dr. SN Medical College', distance: '0.2 km', category: 'Hospital' },
      { name: 'Shastri Circle Banks & Hubs', distance: '0.5 km', category: 'Market' },
      { name: 'AIIMS Jodhpur', distance: '3.1 km', category: 'Hospital' },
      { name: 'Jodhpur Railway Station', distance: '4.0 km', category: 'Transport' },
    ],
    agent: {
      name: 'Sunil Chouhan',
      role: 'Commercial Lead Specialist',
      phone: '+91 98765 43210',
      whatsapp: '+91 98765 43210',
      email: 'sunil.kp@gmail.com',
      image: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=400&q=80',
    },
    dateListed: '2026-07-25',
  },
  {
    id: 'prop-3',
    title: 'Sunrise Heights Modern 3 BHK Apartment',
    price: 28000,
    period: '/mo',
    displayPrice: '₹28,000/mo',
    category: 'Rental',
    propertyType: 'Apartment',
    status: 'For Rent',
    location: 'Ratanada, Jodhpur',
    address: 'Flat 502, Sunrise Towers, Residency Road, Ratanada, Jodhpur',
    areaSqFt: 1850,
    bedrooms: 3,
    bathrooms: 3,
    parking: 1,
    facing: 'East Facing',
    floor: '5th Floor of 9',
    furnishedStatus: 'Semi-Furnished',
    isExclusive: false,
    tag: 'FAMILY FAVORITE',
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80',
    ],
    description: 'Spacious 3 BHK apartment with breathtaking views of Mehrangarh Fort skyline in Ratanada. Includes wood work wardrobes, modular kitchen with chimney, AC points in all rooms, intercom, clubhouse access, and children play area.',
    amenities: [
      'Mehrangarh Fort Sunset View Balcony',
      'Modular Kitchen with Exhaust Chimney',
      'Clubhouse & Gym Access',
      'Children Play Area & Jogging Track',
      'Power Backup for Elevators',
      'Intercom & Video Door Phone',
      'Covered Parking Slot'
    ],
    nearbyPlaces: [
      { name: 'Ratanada Ganesh Temple', distance: '0.8 km', category: 'Market' },
      { name: 'Jodhpur Defense Laboratory', distance: '1.2 km', category: 'Transport' },
      { name: 'Jodhpur Airport', distance: '3.0 km', category: 'Airport' },
      { name: 'Railway Station', distance: '2.5 km', category: 'Transport' }
    ],
    agent: {
      name: 'Ramesh Gehlot',
      role: 'Senior Rental Advisor',
      phone: '+91 98765 43210',
      whatsapp: '+91 98765 43210',
      email: 'ramesh.kp@gmail.com',
      image: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=400&q=80',
    },
    dateListed: '2026-07-28',
  },
  {
    id: 'prop-4',
    title: 'High-Footfall Ground Floor Retail Showroom',
    price: 120000,
    period: '/mo',
    displayPrice: '₹1.20 Lakh/mo',
    category: 'Commercial',
    propertyType: 'Retail Showroom',
    status: 'For Rent',
    location: 'Pal Road, Jodhpur',
    address: 'Ground Floor, Pal Main Road Commercial Plaza, Near Kheme Ka Kua',
    areaSqFt: 2200,
    bathrooms: 2,
    parking: 5,
    facing: 'Main Pal Road Frontage (35 Ft Glass Frontage)',
    floor: 'Ground Floor',
    furnishedStatus: 'Bare Shell',
    isHotDeal: true,
    tag: 'PRIME SHOWROOM',
    images: [
      'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1567449303078-57ad995bd301?auto=format&fit=crop&w=1200&q=80',
    ],
    description: 'Prime commercial retail showroom space on high-traffic Pal Road. Features 35 feet clear glass front display, double height ceiling (14 ft), ample customer parking in front, ideal for apparel brands, electronics, jewelry, bank branches, or car showrooms.',
    amenities: [
      '35 Feet Glass Showroom Frontage',
      '14 Feet Double Height Ceiling',
      'Heavy Footfall Traffic Location',
      'Ample Customer Parking Frontage',
      '3 Phase Commercial Power Connection',
      'Fire Safety Hydrants Installed',
      'Approved for Retail & Banking Use'
    ],
    nearbyPlaces: [
      { name: 'Kheme Ka Kua Circle', distance: '0.2 km', category: 'Market' },
      { name: 'DPS School Jodhpur', distance: '1.5 km', category: 'School' },
      { name: 'AIIMS Jodhpur', distance: '2.8 km', category: 'Hospital' }
    ],
    agent: {
      name: 'Sunil Chouhan',
      role: 'Commercial Lead Specialist',
      phone: '+91 98765 43210',
      whatsapp: '+91 98765 43210',
      email: 'sunil.kp@gmail.com',
      image: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=400&q=80',
    },
    dateListed: '2026-07-18',
  },
  {
    id: 'prop-5',
    title: 'Luxury 2 BHK Furnished Flat Near AIIMS',
    price: 22000,
    period: '/mo',
    displayPrice: '₹22,000/mo',
    category: 'Rental',
    propertyType: 'Apartment',
    status: 'For Rent',
    location: 'AIIMS Road, Jodhpur',
    address: 'Block B, Green Valley Enclave, Near AIIMS Hospital, Basni',
    areaSqFt: 1200,
    bedrooms: 2,
    bathrooms: 2,
    parking: 1,
    facing: 'North Facing',
    floor: '2nd Floor of 6',
    furnishedStatus: 'Furnished',
    isExclusive: false,
    tag: 'IDEAL FOR DOCTORS',
    images: [
      'https://images.unsplash.com/photo-1502005229762-cf1b2da7c5d6?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1200&q=80',
    ],
    description: 'Fully furnished 2 BHK apartment located just 500 meters from AIIMS Jodhpur. Equipped with double beds with mattress, Smart TV, sofa set, refrigerator, washing machine, water purifier, wardrobes, and RO system. Designed specifically for resident doctors, faculty, and medical students.',
    amenities: [
      '500 Meters from AIIMS Gate',
      'Fully Furnished with Electronics',
      'RO Drinking Water System',
      'Geysers in Both Bathrooms',
      'Covered Parking Space',
      'CCTV Monitoring & Gated Entry',
      'Daily Garbage Collection'
    ],
    nearbyPlaces: [
      { name: 'AIIMS Jodhpur Main Campus', distance: '0.5 km', category: 'Hospital' },
      { name: 'Basni Railway Station', distance: '2.0 km', category: 'Transport' },
      { name: 'MIA Industrial Area', distance: '1.8 km', category: 'Market' }
    ],
    agent: {
      name: 'Pooja Sharma',
      role: 'Residential Property Manager',
      phone: '+91 98765 43210',
      whatsapp: '+91 98765 43210',
      email: 'pooja.kp@gmail.com',
      image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
    },
    dateListed: '2026-07-29',
  },
  {
    id: 'prop-6',
    title: 'Spacious Industrial Warehouse & Logistics Godown',
    price: 150000,
    period: '/mo',
    displayPrice: '₹1.50 Lakh/mo',
    category: 'Industrial',
    propertyType: 'Warehouse',
    status: 'For Rent',
    location: 'Basni Phase 2, Jodhpur',
    address: 'Plot 104, Heavy Industrial Area, Basni Phase 2, Jodhpur',
    areaSqFt: 10000,
    bathrooms: 2,
    parking: 8,
    facing: 'North Facing Wide Road',
    floor: 'Ground Heavy RCC Floor',
    furnishedStatus: 'Unfurnished',
    isExclusive: true,
    tag: 'LOGISTICS READY',
    images: [
      'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1553413077-190dd305871c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80',
    ],
    description: '10,000 Sq.Ft industrial warehouse godown with 24 feet clear ceiling height, heavy-duty trimix floor, dock loading gates for trailers, office cabin, guard room, and 50 HP power load approved. Ideal for logistics, FMCG distribution, handicap furniture assembly, or textile storage.',
    amenities: [
      '24 Feet Clear Ceiling Height',
      'Heavy-Duty Industrial Trimix Flooring',
      'Container & Trailer Dock Loading Gates',
      '50 HP Industrial Power Sanction',
      'Security Guard Cabin & Office Space',
      'Fire Hydrant & Smoke Sensors',
      'Wide 60-Ft Access Road'
    ],
    nearbyPlaces: [
      { name: 'Basni Inland Container Depot (ICD)', distance: '1.5 km', category: 'Transport' },
      { name: 'Jodhpur Pali Highway', distance: '2.0 km', category: 'Transport' },
      { name: 'MIA Trade Centre', distance: '1.0 km', category: 'Market' }
    ],
    agent: {
      name: 'Sunil Chouhan',
      role: 'Commercial Lead Specialist',
      phone: '+91 98765 43210',
      whatsapp: '+91 98765 43210',
      email: 'sunil.kp@gmail.com',
      image: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=400&q=80',
    },
    dateListed: '2026-07-15',
  },
  {
    id: 'prop-7',
    title: 'Modern 3 BHK Independent House with Car Porch',
    price: 35000,
    period: '/mo',
    displayPrice: '₹35,000/mo',
    category: 'Residential',
    propertyType: 'Independent House',
    status: 'For Rent',
    location: 'Chopasni Housing Board, Jodhpur',
    address: 'Sector 14, Chopasni Housing Board, Near First Step School',
    areaSqFt: 2200,
    bedrooms: 3,
    bathrooms: 3,
    parking: 2,
    facing: 'East Facing',
    floor: 'Ground + First Floor',
    furnishedStatus: 'Semi-Furnished',
    isHotDeal: false,
    tag: 'CORNER PLOT',
    images: [
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80',
    ],
    description: 'Beautiful corner independent duplex house in Chopasni Housing Board. Features high ceiling living area, modular kitchen, open terrace for evening tea, water storage underground tank (10,000 Liters), and boundary wall security.',
    amenities: [
      'Corner Plot Extra Light & Ventilation',
      '10,000 Ltr Underground Water Tank',
      'Spacious Open Roof Terrace',
      'Semi-Modular Kitchen with Cabinets',
      'Covered Car Porch',
      'Quiet Residential Colony',
      'Vastu Compliant Layout'
    ],
    nearbyPlaces: [
      { name: 'First Step School', distance: '0.3 km', category: 'School' },
      { name: 'Chopasni Market Circle', distance: '0.6 km', category: 'Market' },
      { name: 'AIIMS Hospital', distance: '4.5 km', category: 'Hospital' }
    ],
    agent: {
      name: 'Ramesh Gehlot',
      role: 'Senior Rental Advisor',
      phone: '+91 98765 43210',
      whatsapp: '+91 98765 43210',
      email: 'ramesh.kp@gmail.com',
      image: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=400&q=80',
    },
    dateListed: '2026-07-22',
  },
  {
    id: 'prop-8',
    title: 'Boutique IT Park Office & Coworking Floor',
    price: 75000,
    period: '/mo',
    displayPrice: '₹75,000/mo',
    category: 'Office Space',
    propertyType: 'Office Suite',
    status: 'For Rent',
    location: 'Paota, Jodhpur',
    address: '2nd Floor, Royal Arcade, Near BGL Hospital, Paota C Road',
    areaSqFt: 2100,
    bathrooms: 3,
    parking: 3,
    facing: 'Main Paota C Road',
    floor: '2nd Floor',
    furnishedStatus: 'Furnished',
    isExclusive: true,
    tag: 'PLUG & PLAY IT OFFICE',
    images: [
      'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1527192491265-7e15c55b1ed2?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1200&q=80',
    ],
    description: 'Fully plug and play IT office space in Paota. Includes 28 ergonomic mesh chairs, high speed LAN network cabling, UPS backup, pantry with microwave and coffee vending machine, and 2 executive cabins.',
    amenities: [
      '28 Plug & Play Workstations',
      'Dedicated UPS Power Backup',
      'Executive Cabins & Meeting Room',
      'Cafeteria with Coffee Machine',
      'CCTV & Smart Card Entry',
      'Near Paota Bus Stand Hub'
    ],
    nearbyPlaces: [
      { name: 'Paota Central Bus Stand', distance: '0.4 km', category: 'Transport' },
      { name: 'High Court Jodhpur', distance: '1.8 km', category: 'Market' },
      { name: 'Jodhpur Railway Station', distance: '3.2 km', category: 'Transport' }
    ],
    agent: {
      name: 'Sunil Chouhan',
      role: 'Commercial Lead Specialist',
      phone: '+91 98765 43210',
      whatsapp: '+91 98765 43210',
      email: 'sunil.kp@gmail.com',
      image: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=400&q=80',
    },
    dateListed: '2026-07-26',
  }
];

export const AREA_PROFILES: AreaProfile[] = [
  {
    id: 'area-sardarpura',
    name: 'Sardarpura',
    tagline: 'Jodhpur’s High-Street Fashion, Dining & Luxury Residence Hub',
    description: 'Sardarpura is the heart of Jodhpur\'s commercial and premium residential life. Famous for C-Road, B-Road, Jaljog Circle, and heritage villas, it is the top choice for luxury home rentals, fashion retail brands, and corporate offices.',
    image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Luxury Villas', 'High-Street Retail', 'Top Dining & Cafes', 'Corporate Offices'],
    avgRentResidential: '₹25,000 - ₹90,000/mo',
    avgRentCommercial: '₹50,000 - ₹2.5 Lakh/mo',
    featuredPropertyCount: 42,
  },
  {
    id: 'area-shastri-nagar',
    name: 'Shastri Nagar',
    tagline: 'Medical Hub, Executive Homes & Corporate Offices',
    description: 'Home to Dr. SN Medical College and Shastri Circle, Shastri Nagar offers tranquil upscale residential colonies alongside prime healthcare and legal corporate office suites.',
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Doctor Residences', 'Corporate Office Towers', 'Bank Branches', '3 BHK Apartments'],
    avgRentResidential: '₹20,000 - ₹60,000/mo',
    avgRentCommercial: '₹40,000 - ₹1.8 Lakh/mo',
    featuredPropertyCount: 38,
  },
  {
    id: 'area-ratanada',
    name: 'Ratanada',
    tagline: 'Ganesh Temple Vicinity, Defence Colony & Fort Views',
    description: 'Ratanada is favored for its royal heritage vibe, proximity to the Defense Laboratory, Air Force Station, Jodhpur Airport, and scenic Mehrangarh Fort skyline views.',
    image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Skyline Apartments', 'Airport Access', 'Heritage Guest Houses', 'Quiet Colonies'],
    avgRentResidential: '₹18,000 - ₹50,000/mo',
    avgRentCommercial: '₹35,000 - ₹1.2 Lakh/mo',
    featuredPropertyCount: 29,
  },
  {
    id: 'area-pal-road',
    name: 'Pal Road',
    tagline: 'Rapidly Growing Commercial Corridor & Modern Gated Townships',
    description: 'Pal Road is the fastest-expanding commercial and multi-story apartment corridor in Jodhpur. Features DPS School, major hospital chains, and modern gated societies.',
    image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Ground Floor Showrooms', 'Gated Community Flats', 'Supermarkets', 'Educational Hubs'],
    avgRentResidential: '₹15,000 - ₹40,000/mo',
    avgRentCommercial: '₹60,000 - ₹3.0 Lakh/mo',
    featuredPropertyCount: 51,
  },
  {
    id: 'area-aiims-road',
    name: 'AIIMS & Basni',
    tagline: 'Medical Staff Accommodation & Heavy Industrial Logistics',
    description: 'AIIMS Road and Basni Industrial Phase 1 & 2 serve healthcare professionals with furnished apartments, while housing large warehouses and logistics godowns for export units.',
    image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Doctor Furnished Flats', 'Industrial Warehouses', 'Logistics Depots', 'Handicrafts Storage'],
    avgRentResidential: '₹14,000 - ₹32,000/mo',
    avgRentCommercial: '₹50,000 - ₹4.0 Lakh/mo',
    featuredPropertyCount: 45,
  },
  {
    id: 'area-paota',
    name: 'Paota & High Court Circle',
    tagline: 'Transport Hub, Legal Chambers & High-Footfall Commercial',
    description: 'Connected directly to the High Court and Central Bus Stand, Paota is an bustling hub for law offices, hotels, coaching institutes, and high-footfall commercial spaces.',
    image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80',
    popularFor: ['Advocate Offices', 'Coaching Institutes', 'Hotels & PG Accommodations', 'Retail Complexes'],
    avgRentResidential: '₹12,000 - ₹35,000/mo',
    avgRentCommercial: '₹30,000 - ₹1.5 Lakh/mo',
    featuredPropertyCount: 33,
  },
];

export const SERVICES_DATA: ServiceItem[] = [
  {
    id: 'serv-1',
    title: 'Residential Property Rental',
    iconName: 'Home',
    badge: 'MOST POPULAR',
    shortDesc: 'Premium 1/2/3/4 BHK flats, luxury heritage villas, and independent houses across prime Jodhpur localities.',
    fullDesc: 'We specialize in finding verified residential rental properties for families, corporate transfers, doctors, and expats. Complete background checks and owner negotiation handled seamlessly.',
    benefits: [
      '100% Physically Verified Properties',
      'Transparent Brokerage Terms with Zero Hidden Charges',
      'Owner Negotiation & Key Handover Assistance',
      'Move-in Inspection & Inventory Checklist Support'
    ],
    processSteps: ['Requirement Consultation', 'Curated Property Visits', 'Price Negotiation', 'Rent Agreement & Move-In'],
    targetAudience: 'Families, Corporate Executives, AIIMS Doctors, Defense Personnel',
  },
  {
    id: 'serv-2',
    title: 'Commercial Office Space Leasing',
    iconName: 'Building2',
    badge: 'CORPORATE CHOICE',
    shortDesc: 'Plug-and-play offices, bare shell floors, glass towers, and IT park suites in Shastri Nagar & Sardarpura.',
    fullDesc: 'Custom workspace solutions for IT firms, law offices, banks, and corporate branches. We match your headcount, parking, and compliance needs.',
    benefits: [
      'Floor Plan & Headcount Optimization',
      'Commercial Lease Deed Legal Vetting',
      '3-Phase Power & Lift Load Clearance',
      'Basement & Open Parking Allocation'
    ],
    processSteps: ['Commercial Briefing', 'Site Inspection & CAD Analysis', 'Lease Term Structuring', 'Possession & Handover'],
    targetAudience: 'IT Companies, CAs, Law Firms, Regional Corporate Offices',
  },
  {
    id: 'serv-3',
    title: 'Retail Showroom & High-Street Shops',
    iconName: 'Store',
    badge: 'HIGH FOOTFALL',
    shortDesc: 'Prime ground floor showroom spaces on Pal Road, C-Road Sardarpura, and Main Highway Corridors.',
    fullDesc: 'Get maximum footfall for retail brands, restaurants, banks, and jewelry showrooms with high-visibility frontage in Jodhpur’s busiest trade corridors.',
    benefits: [
      'Frontage Visibility & Footfall Analytics',
      'Signage Approval & Municipal Clearances',
      'Long-Term Lease Stability (3-9 Years)',
      'High Ceiling & Glass Frontage Options'
    ],
    processSteps: ['Brand Requirement Audit', 'High-Street Site Visits', 'LOI & Commercial Term Finalization', 'Store Fitting Access'],
    targetAudience: 'Fashion Brands, Electronics Chains, Jewelry Stores, Restaurants',
  },
  {
    id: 'serv-4',
    title: 'Industrial Property & Logistics Godowns',
    iconName: 'Warehouse',
    badge: 'HEAVY INDUSTRIAL',
    shortDesc: 'Heavy-duty warehouses, handicraft export units, and logistics godowns in Basni and Boranada.',
    fullDesc: 'Warehouse facilities equipped with high ceilings, dock loading, heavy power load approvals, and wide access roads for trailer transport.',
    benefits: [
      'Container & Dock Loading Compatibility',
      'Heavy RCC Flooring for Storage',
      'RIICO & Industrial Zoning Approvals',
      'Fire Safety Hydrants & CCTV Setup'
    ],
    processSteps: ['Logistics Capacity Study', 'Godown Inspections', 'Power & Lease Approval', 'Industrial Handover'],
    targetAudience: 'Export Units, E-commerce Logistics, FMCG Distributors, Furniture Mfrs',
  },
  {
    id: 'serv-5',
    title: 'Rent Agreement & Legal Deed Assistance',
    iconName: 'FileText',
    badge: 'FAST 24-HOUR SERVICE',
    shortDesc: 'Government e-stamping, police verification, rent deed drafting, and doorstep notary delivery.',
    fullDesc: 'Hassle-free 11-month or long-term rent agreement drafting with legal clause protection for both tenant and owner in Jodhpur.',
    benefits: [
      'Government E-Stamp Duty Calculation',
      'Standardized Tenant-Owner Protection Clauses',
      'Online Police Verification Assistance',
      'Doorstep Delivery in Jodhpur City'
    ],
    processSteps: ['Submit ID & Terms', 'Draft Review via WhatsApp', 'E-Stamping & Signature', 'Doorstep Document Delivery'],
    targetAudience: 'Tenants, Landlords, NRI Property Owners',
  },
  {
    id: 'serv-6',
    title: 'End-to-End Property Management for Owners',
    iconName: 'ShieldCheck',
    badge: 'FOR LANDLORDS / NRIs',
    shortDesc: 'Complete property care for NRI and outstation owners: tenant placement, rent collection, and repairs.',
    fullDesc: 'Sit back and enjoy passive rental income. Karni Property manages tenant screening, monthly rent collection, property maintenance, and regular photographic updates.',
    benefits: [
      'Strict Tenant Background & Employment Verification',
      'Guaranteed On-Time Rent Collection & Direct Transfer',
      'Bi-annual Property Health Inspection',
      'Plumbing, Painting, & Repair Maintenance Team'
    ],
    processSteps: ['Property Audit & Rent Estimate', 'Marketing & Tenant Screening', 'Lease Execution', 'Monthly Management & Reporting'],
    targetAudience: 'NRI Landlords, Outstation Owners, Multiple Property Investors',
  },
  {
    id: 'serv-7',
    title: 'Short-Term, PG & Executive Co-Living Stays',
    iconName: 'BedDouble',
    badge: 'STUDENTS & EXECUTIVES',
    shortDesc: 'Fully furnished PG rooms, studio apartments, and executive co-living stays with high-speed WiFi and meals near AIIMS & Basni.',
    fullDesc: 'Customized short-term and student accommodation rental options with verified amenities, AC rooms, 24/7 security, mess facility, and daily housekeeping.',
    benefits: [
      'Single & Sharing Furnished AC Rooms',
      'Proximity to AIIMS Jodhpur & Engineering Colleges',
      'Daily Room Cleaning & Hygienic Food Mess Option',
      'Flexible 3 to 12 Month Rental Tenure'
    ],
    processSteps: ['Location & Budget Preference', 'Virtual/In-Person Room Tour', 'Token & Verification', 'Instant Check-in'],
    targetAudience: 'Medical Students, AIIMS Interns, IT Professionals, Short-Term Project Consultants',
  },
  {
    id: 'serv-8',
    title: 'Digital Property Inspection & Inventory Audit',
    iconName: 'ClipboardCheck',
    badge: 'DEPOSIT PROTECTION',
    shortDesc: 'Independent 75-point photo & video property condition check prior to tenancy move-in or move-out.',
    fullDesc: 'Protect your security deposit and avoid landlord-tenant disputes with our official Karni Property Digital Move-In Inspection Report documenting pre-existing condition, electrical fittings, plumbing, and appliances.',
    benefits: [
      '75-Point Comprehensive Property Audit',
      'High-Resolution Photo & Video Proof Package',
      'Official Signed Digital Inspection Certificate',
      'Zero-Dispute Deposit Refunds at Lease Completion'
    ],
    processSteps: ['Inspection Booking', 'On-Site KP Auditor Visit', 'Digital Report Generation', 'Dual Sign-off Delivery'],
    targetAudience: 'Tenants safeguarding security deposits, Landlords preserving property condition',
  },
  {
    id: 'serv-9',
    title: 'Tenant Verification & Police Clearance Express',
    iconName: 'UserCheck',
    badge: 'SAFETY & TRUST',
    shortDesc: 'Rapid police verification, Aadhaar/PAN authentication, civil record check, and employer verification in Jodhpur.',
    fullDesc: 'Safety first! We conduct exhaustive background checks on prospective tenants including identity verification, employment status, local police station clearance, and previous landlord references.',
    benefits: [
      'Official Rajasthan Police Verification Submission',
      'Aadhaar & PAN Government Identity Validation',
      'Employment & Salary Slip Authenticity Check',
      'Fast 48-Hour Turnaround Time'
    ],
    processSteps: ['Upload Tenant Documents', 'Government ID & Record Check', 'Local Police Portal Submission', 'Clearance Certificate Issued'],
    targetAudience: 'House Owners, Commercial Landlords, Gated Society Associations',
  }
];

export const RENTAL_SERVICE_OPTIONS = [
  {
    category: 'Tenants & Home Seekers',
    tag: 'Tenant Solutions',
    options: [
      {
        id: 'opt-tenant-1',
        name: 'Express House Hunting Package',
        desc: 'Dedicated KP agent + private car property visits + instant deal closing.',
        price: 'Included in Standard Brokerage',
        icon: 'Car',
        badge: 'POPULAR CHOICE',
      },
      {
        id: 'opt-tenant-2',
        name: 'Move-In Ready Furnished Guarantee',
        desc: 'Curated 100% furnished homes with AC, TV, Refrigerator, RO & Bedding.',
        price: '₹15,000 - ₹45,000/mo',
        icon: 'Tv',
        badge: 'ZERO SETUP NEEDED',
      },
      {
        id: 'opt-tenant-[#]',
        name: 'Student & Doctor PG / Co-Living Option',
        desc: 'AC single/twin sharing room with food, WiFi & security near AIIMS/Basni.',
        price: '₹7,500 - ₹14,000/mo',
        icon: 'GraduationCap',
        badge: 'ALL INCLUSIVE',
      },
      {
        id: 'opt-tenant-4',
        name: 'Move-in Condition Audit & Deposit Shield',
        desc: '75-point photo inspection report to guarantee 100% security deposit refund.',
        price: '₹1,499 One-time',
        icon: 'ShieldCheck',
        badge: 'DEPOSIT SAFEGUARD',
      },
    ],
  },
  {
    category: 'Property Landlords & Owners',
    tag: 'Owner Solutions',
    options: [
      {
        id: 'opt-owner-1',
        name: '14-Day Verified Tenant Guarantee',
        desc: 'Fast tenant placement via targeted digital marketing + corporate network.',
        price: '1 Month Brokerage',
        icon: 'Users',
        badge: 'FAST OCCUPANCY',
      },
      {
        id: 'opt-owner-2',
        name: 'Complete Hands-Off Property Management',
        desc: 'Monthly rent collection, maintenance calls, routine visits & direct bank transfer.',
        price: '8% Monthly Rent',
        icon: 'Building2',
        badge: 'PASSIVE INCOME',
      },
      {
        id: 'opt-owner-3',
        name: 'Express Tenant Police Verification',
        desc: 'Aadhaar, PAN & Rajasthan Police portal verification certificate.',
        price: '₹999 per tenant',
        icon: 'UserCheck',
        badge: '100% SECURE',
      },
      {
        id: 'opt-owner-4',
        name: 'NRI Property Watch & Maintenance',
        desc: 'Bi-monthly HD video reports, deep cleaning before tenant entry, tax support.',
        price: 'Custom Annual Plan',
        icon: 'Globe',
        badge: 'FOR NRI OWNERS',
      },
    ],
  },
  {
    category: 'Legal & Agreement Services',
    tag: 'E-Stamping & Legal',
    options: [
      {
        id: 'opt-legal-1',
        name: 'Standard 11-Month Rent Agreement',
        desc: 'Drafted by real estate legal expert, e-stamped and delivered to door in 24 hours.',
        price: '₹1,199 (Inc. Stamp Duty)',
        icon: 'FileText',
        badge: '24-HOUR DELIVERY',
      },
      {
        id: 'opt-legal-2',
        name: 'Commercial Registered Lease Deed',
        desc: 'Multi-year commercial lease drafting, sub-registrar registration & GST compliant.',
        price: 'As per lease value',
        icon: 'Briefcase',
        badge: 'COMMERCIAL LEASE',
      },
      {
        id: 'opt-legal-3',
        name: 'Notarized Rent Agreement + Doorstep Courier',
        desc: 'Government notary stamp with physical copy sent anywhere in Jodhpur.',
        price: '₹1,499 Total',
        icon: 'CheckCircle2',
        badge: 'NOTARIZED DEED',
      },
    ],
  },
];

export const TESTIMONIALS_DATA: Testimonial[] = [
  {
    id: 'test-1',
    author: 'Dr. Vikrant Mehta',
    role: 'Associate Professor, AIIMS Jodhpur',
    rating: 5,
    date: '2 weeks ago',
    location: 'Basni / AIIMS Road',
    comment: 'Karni Property helped me find a fully furnished 2 BHK apartment within 500 meters of AIIMS Jodhpur in under 24 hours! Rameshji handled the rent agreement, police verification, and key handover smoothly. Unmatched professionalism in Jodhpur real estate.',
    avatar: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=200&q=80',
    verifiedTag: 'Verified Tenant',
  },
  {
    id: 'test-2',
    author: 'Sunita & Arvind Mathur',
    role: 'NRI Property Owners (Dubai)',
    rating: 5,
    date: '1 month ago',
    location: 'Sardarpura Villa',
    comment: 'Living in Dubai, managing our ancestral villa in Sardarpura was always a headache until we hired Karni Property. They secured a high-profile corporate tenant, drafted a bulletproof rent agreement, and transfer monthly rent on the 1st of every month without fail.',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80',
    verifiedTag: 'NRI Property Owner',
  },
  {
    id: 'test-3',
    author: 'Karan Singhal',
    role: 'Founder, TechSpire Solutions',
    rating: 5,
    date: '1 month ago',
    location: 'Shastri Nagar Office',
    comment: 'Finding a 20-seater plug-and-play office space with ample parking in Shastri Nagar felt impossible until Sunil from Karni Property stepped in. He showed us 3 ready-to-move options on day one. We signed the lease deed within 3 days.',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    verifiedTag: 'Commercial Client',
  },
  {
    id: 'test-4',
    author: 'Priya Rajpurohit',
    role: 'Fashion Designer & Retailer',
    rating: 5,
    date: '3 months ago',
    location: 'Pal Road Showroom',
    comment: 'We wanted a 30-ft glass frontage store on main Pal Road for our ethnic fashion brand. Karni Property got us an unbelievable ground floor location with great footfall and very fair security deposit terms.',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    verifiedTag: 'Retail Tenant',
  },
];

export const FAQ_DATA: FAQItem[] = [
  {
    id: 'faq-1',
    category: 'Renting',
    question: 'What documents are required to rent a residential property in Jodhpur through Karni Property?',
    answer: 'For tenants in Jodhpur, standard documents required include: Aadhaar Card, PAN Card, passport size photograph, employment/company ID or appointment letter, and previous address proof. For students or doctors, institute/AIIMS ID is accepted.',
  },
  {
    id: 'faq-2',
    category: 'Agreement',
    question: 'How long does it take to draft and execute a legal Rent Agreement in Jodhpur?',
    answer: 'At Karni Property, we provide 24-hour e-stamping and rent agreement delivery. Once owner and tenant terms are finalized, our team drafts the agreement with standard legal clauses, arranges e-stamp paper, coordinates digital/physical signatures, and assists with tenant police verification.',
  },
  {
    id: 'faq-3',
    category: 'Commercial',
    question: 'What is the standard security deposit and rent increment percentage in Jodhpur commercial leases?',
    answer: 'Standard commercial security deposit in prime Jodhpur areas (Sardarpura, Pal Road, Shastri Nagar) ranges from 2 to 4 months of rent. The annual rent escalation clause is typically 5% to 10% per annum, or 15% every 3 years for long-term leases.',
  },
  {
    id: 'faq-4',
    category: 'Owners',
    question: 'How does Karni Property screen tenants for landlords and NRI property owners?',
    answer: 'We follow a strict 4-step tenant verification framework: 1) Identity & Aadhaar verification, 2) Employment background check and monthly income proof, 3) Past landlord reference check, and 4) Mandatory Jodhpur Police tenant verification submission.',
  },
  {
    id: 'faq-5',
    category: 'General',
    question: 'What are the brokerage charges of Karni Property in Jodhpur?',
    answer: 'Our brokerage policy is 100% transparent: For residential rentals (11-month lease), standard brokerage is 1 month rent. For commercial leases, brokerage is 1 month rent or customized based on long-term lease agreement length.',
  },
  {
    id: 'faq-6',
    category: 'Renting',
    question: 'Are bachelor accommodation, student flats, and doctor flats available near AIIMS and Medical College?',
    answer: 'Yes! We maintain an updated database of doctor-friendly and bachelor-permitted 1 BHK, 2 BHK, and 3 BHK flats near AIIMS Jodhpur (Basni), Dr. SN Medical College (Shastri Nagar), and IIT Jodhpur bus routes.',
  },
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: 'blog-1',
    slug: 'jodhpur-rental-market-trends-2026',
    title: 'Jodhpur Real Estate Rental Trends 2026: Sardarpura vs. Pal Road vs. AIIMS Corridor',
    category: 'Market Insights',
    date: 'July 15, 2026',
    readTime: '5 min read',
    author: 'Karni Property Research Team',
    image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80',
    excerpt: 'An in-depth analysis of rental yield trends, top commercial hotspots, and high-demand residential sectors across Jodhpur in 2026.',
    content: [
      'Jodhpur’s real estate landscape has experienced phenomenal transformation over the last three years. Driven by expanding healthcare infrastructure at AIIMS Jodhpur, surging legal corporate setups near the High Court, and growing handicraft export hubs, rental demand in prime sectors has surged by over 18% year-on-year.',
      'Sardarpura continues to command top rental yields for luxury villas and high-street fashion retail showrooms. Meanwhile, Pal Road has emerged as the premier choice for families looking for modern 2/3 BHK gated community flats with elevators and clubhouse amenities.',
      'For investors, commercial office suites in Shastri Nagar and Basni warehouses are offering attractive 6.5% to 8% rental yields. Here is a breakdown of average rents per square foot across top Jodhpur zones.'
    ],
    tags: ['Jodhpur Real Estate', 'Property Rent', 'Sardarpura', 'Pal Road', 'AIIMS Jodhpur'],
  },
  {
    id: 'blog-2',
    slug: 'rent-agreement-rules-jodhpur-rajasthan',
    title: 'Essential Guide to Rent Agreements & Tenant Police Verification in Rajasthan',
    category: 'Legal & Guidelines',
    date: 'June 28, 2026',
    readTime: '4 min read',
    author: 'Legal Team, Karni Property',
    image: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?auto=format&fit=crop&w=800&q=80',
    excerpt: 'Learn why an 11-month rent agreement is standard in Rajasthan, how e-stamping works, and how to avoid legal disputes as a landlord or tenant.',
    content: [
      'Under the Rajasthan Rent Control Act and Indian Registration Act, agreements leased for 11 months do not mandate registration at the Sub-Registrar office, making them cost-effective and legally flexible.',
      'However, e-stamping on appropriate non-judicial stamp value (typically ₹100 or ₹500 in Rajasthan depending on rent amount) is strictly mandatory for the agreement to hold evidentiary value in court.',
      'Furthermore, Jodhpur Police mandates online or offline tenant verification for all residential rentals to ensure security. Here is the step-by-step procedure to complete agreement drafting in under 24 hours.'
    ],
    tags: ['Rent Agreement', 'E-Stamp Rajasthan', 'Police Verification', 'Tenant Protection'],
  },
  {
    id: 'blog-3',
    slug: 'top-commercial-hubs-jodhpur-office-showroom',
    title: 'Top 5 Commercial Hubs in Jodhpur for Offices, Showrooms & Bank Branches',
    category: 'Commercial Real Estate',
    date: 'May 10, 2026',
    readTime: '6 min read',
    author: 'Sunil Chouhan',
    image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80',
    excerpt: 'Comparing footfall, parking facilities, and lease rates across Shastri Circle, Sardarpura C-Road, Pal Main Road, Paota, and Chopasni Road.',
    content: [
      'Choosing the right commercial location in Jodhpur can dictate the growth trajectory of your business. Retail apparel brands thrive on Sardarpura C-Road due to dense footfall and high purchasing power.',
      'For IT companies, financial services, and law firms, glass-front towers around Shastri Circle provide high visibility, lift access, and dedicated basement parking.',
      'If you need large ground floor retail spaces exceeding 2,000 sq ft, Pal Road provides the best value per square foot with spacious front parking.'
    ],
    tags: ['Commercial Office', 'Showroom Rent Jodhpur', 'Shastri Nagar', 'Business Expansion'],
  },
];
